/* CREATING NEW TABLE em_flights */
create table em_flights (
YEAR int,
MONTH int,  
DAY int,  
DAY_OF_WEEK int,  
AIRLINE varchar(5),
FLIGHT_NUMBER int,
TAIL_NUMBER varchar (10),
ORIGIN_AIRPORT varchar (7),
DESTINATION_AIRPORT varchar (7),
SCHEDULED_DEPARTURE int,
DEPARTURE_TIME float,
DEPARTURE_DELAY float,
TAXI_OUT float,
WHEELS_OFF float,
SCHEDULED_TIME float,
ELAPSED_TIME float,
AIR_TIME float,
DISTANCE  int,
WHEELS_ON  float,
TAXI_IN float,
SCHEDULED_ARRIVAL float,
ARRIVAL_TIME float,
ARRIVAL_DELAY float,
DIVERTED   float,
CANCELLED  float,
CANCELLATION_REASON  varchar(5),
AIR_SYSTEM_DELAY float,
SECURITY_DELAY float,
AIRLINE_DELAY float,
LATE_AIRCRAFT_DELAY float,
WEATHER_DELAY float
);

/* UPLOADING DATA IN TO em_flights TABLE */

COPY em_flights
FROM 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/Final_project_data_archive/flights.csv'
WITH (
    FORMAT csv,
    HEADER,
    DELIMITER ',',
    QUOTE '"'
);


alter table em_flights add column SCHEDULED_DATE date;

UPDATE em_flights SET SCHEDULED_DATE = TO_DATE(
    LPAD(YEAR:: TEXT, 4, '0') || '-' ||
    LPAD(MONTH:: TEXT, 2, '0') || '-' ||
    LPAD(DAY:: TEXT, 2, '0'), 'YYYY-MM-DD')
WHERE SCHEDULED_DATE IS NULL;

-- -------

-- WORKING ON SCHEDULED_ARRIVAL COLUMN

ALTER TABLE EM_FLIGHTS ADD COLUMN FORMATED_SCHEDULED_ARRIVAL TIME;

	UPDATE EM_FLIGHTS
		SET FORMATED_SCHEDULED_ARRIVAL = 
			TO_TIMESTAMP(
				CASE 
					WHEN SCHEDULED_ARRIVAL = 2400 THEN '0000'
				    ELSE LPAD(SCHEDULED_ARRIVAL:: TEXT, 4, '0') END,
				'HH24MI'):: TIME;


	ALTER TABLE EM_FLIGHTS 
	DROP COLUMN SCHEDULED_ARRIVAL;
	
	ALTER TABLE EM_FLIGHTS 
	RENAME COLUMN FORMATED_SCHEDULED_ARRIVAL TO SCHEDULED_ARRIVAL;

-- WORKING ON ARRIVAL_TIME COLUMN

ALTER TABLE EM_FLIGHTS ADD COLUMN FORMATED_ARRIVAL_TIME TIME;

	UPDATE EM_FLIGHTS SET 
	FORMATED_ARRIVAL_TIME= TO_TIMESTAMP(
		CASE 
			WHEN ARRIVAL_TIME = 2400 THEN '0000'
		    ELSE LPAD(ARRIVAL_TIME:: TEXT, 4, '0') END,
			'HH24MI')::TIME;

-- SELECT *
-- FROM EM_FLIGHTS WHERE ARRIVAL_TIME IS NULL;


	ALTER TABLE EM_FLIGHTS 
	DROP COLUMN ARRIVAL_TIME;
	
	ALTER TABLE EM_FLIGHTS 
	RENAME COLUMN FORMATED_ARRIVAL_TIME TO ARRIVAL_TIME;


-- WORKING ON SCHEDULE_DEPARTURE COLUMN

ALTER TABLE EM_FLIGHTS ADD COLUMN FORMATED_SCHEDULED_DEPARTURE TIME;

	UPDATE EM_FLIGHTS SET 
	FORMATED_SCHEDULED_DEPARTURE= TO_TIMESTAMP(
		CASE 
			WHEN SCHEDULED_DEPARTURE = 2400 THEN '0000'
		    ELSE LPAD(SCHEDULED_DEPARTURE:: TEXT, 4, '0') END,
			'HH24MI')::TIME;
	
	ALTER TABLE EM_FLIGHTS 
	DROP COLUMN SCHEDULED_DEPARTURE;
	
	ALTER TABLE EM_FLIGHTS 
	RENAME COLUMN FORMATED_SCHEDULED_DEPARTURE TO SCHEDULED_DEPARTURE;


-- WORKING ON DEPARTURE_TIME COLUMN:

ALTER TABLE EM_FLIGHTS ADD COLUMN FORMATED_DEPARTURE_TIME TIME;

	UPDATE EM_FLIGHTS SET 
	FORMATED_DEPARTURE_TIME= TO_TIMESTAMP(
		CASE 
			WHEN DEPARTURE_TIME = 2400 THEN '0000'
		    ELSE LPAD(DEPARTURE_TIME:: TEXT, 4, '0') END,
			'HH24MI')::TIME;
	
	ALTER TABLE EM_FLIGHTS 
	DROP COLUMN DEPARTURE_TIME;
	
	ALTER TABLE EM_FLIGHTS 
	RENAME COLUMN FORMATED_DEPARTURE_TIME TO DEPARTURE_TIME;


-- WORKING ON DEPARTURE_TIME / ARRIVAL_TIME COLUMN 
-- -- FOR CREATING TIME BUCKED:
-- ALTER TABLE EM_FLIGHTS DROP COLUMN ARRIVAL_TIME_BUCKET;

ALTER TABLE EM_FLIGHTS ADD COLUMN DEPARTURE_TIME_BUCKET INT; -- CREATING TIME BUCKED FOR DEPARTURE_TIME

ALTER TABLE EM_FLIGHTS ADD COLUMN ARRIVAL_TIME_BUCKET INT;  -- CREATING TIME BUCKED FOR ARRIVAL_TIME


/* EXTARCTING HOURS FROM DEPARTURE_TIME / ARRIVAL_TIME FOR
DEPARTURE_TIME_BUCKET AND ARRIVAL_TIME_BUCKET COLUMN
*/

UPDATE EM_FLIGHTS 
SET DEPARTURE_TIME_BUCKET = EXTRACT(HOUR FROM DEPARTURE_TIME),
ARRIVAL_TIME_BUCKET = EXTRACT(HOUR FROM ARRIVAL_TIME);





SELECT DISTINCT(EXTRACT(HOUR FROM DEPARTURE_TIME))
FROM EM_FLIGHTS;

SELECT *
FROM EM_FLIGHTS LIMIT 1000;

-- SELECT MAX(SCHEDULED_ARRIVAL) FROM EM_FLIGHTS;


-- DROP TABLE em_flights;
-- SELECT * FROM EM_FLIGHTS LIMIT 100000;
-- SELECT COUNT(*) FROM EM_FLIGHTS;
/* -------------------------------------------------------------------  */

/* CREATING NEW TABLE Airports */

Create table Airports (
IATA_CODE varchar(4),
AIRPORT varchar(78),
CITY varchar(32),
STATE varchar(4),
COUNTRY varchar(4),
LATITUDE float,
LONGITUDE float);

/* UPLOADING DATA IN TO airports TABLE*/

COPY airports
FROM 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/Final_project_data_archive/airports_changed_encode.csv'
WITH (
	 FORMAT csv,
	 HEADER,
	 DELIMITER ',',
	 QUOTE '"'
	 );

/* -------------------------------------------------------------------  */

/* CREATING NEW TABLE Airlines */
Create table Airlines( 
	IATA_CODE varchar(4),
	AIRLINE varchar(28)
	);

-- DROP TABLE Airlines;

/* UPLOADING DATA IN TO Airlines TABLE*/

COPY Airlines
FROM 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/Final_project_data_archive/airlines.csv'
WITH(
	FORMAT csv,
	HEADER,
	DELIMITER ',',
	QUOTE '"'
	);

/* -------------------------------------------------------------------  */

/* DATA OPERATIONS  */


SELECT * FROM EM_FLIGHTS;

/* THE 10th MONTH DATA HAS PROBLEM: 
		ORIGIN_AIRPORTS and ORIGIN_AIRPORTS DATA ARE IN NUMBER FORMAT
*/
SELECT * FROM EM_FLIGHTS WHERE month =10;






/* Problem Statement:
---------------------
1 Analyzing the primary causes and patterns of flight delays 
For strategic operational adjustments: 
Means for what reason in each month how many flights delayed in each month
*/


-- Solution: Finding in each month how many and what types of flights delayed happend.
-- COUNT OF ALL DELAYED FLIGHTS


/* 
THIS CODE WILL NOT GIVE RESULTS, AND/OR LOGIC WILL EITHER 
DECRESES/ INCREASES THE COUNTS
*/
	-- WITH FT_DEPT_CTE AS
	-- 	(SELECT MONTH, 
	-- 	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS,
	-- 	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS,
	-- 	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS,
	-- 	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS,
	-- 	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS,
	-- 	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS,
	-- 	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	-- 	FROM EM_FLIGHTS 
	-- 	WHERE DEPARTURE_DELAY > 0 OR ARRIVAL_DELAY  > 0 OR AIR_SYSTEM_DELAY > 0  OR WEATHER_DELAY > 0 
	-- 	OR LATE_AIRCRAFT_DELAY > 0  OR AIRLINE_DELAY > 0  OR SECURITY_DELAY > 0 
	-- 	GROUP BY MONTH
	-- 	)
	-- SELECT * FROM FT_DEPT_CTE;
/*

ACTUAL CODE

*/

WITH FT_DEPT_CTE AS
	(SELECT MONTH, 
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH
	),
FT_ARRIV_CTE AS
	(SELECT MONTH,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH
	),
FT_WEATH_CTE AS
	(SELECT MONTH, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH
	),

FT_AIRL_CTE AS
	(SELECT MONTH, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH
	),	

FT_SECU_CTE AS
	(SELECT MONTH, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.DEPARTURE_DELAYED_FLIGHTS,
	 F2.ARRIVAL_DELAYED_FLIGHTS,
	 F3.AIR_SYSTEM_DELAYED_FLIGHTS, 
	 F4.WEATHER_DELAYED_FLIGHTS,
	 F5.LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 F6.SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH
	 JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH
	 JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH
	 JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH
	 JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	 
	)	
SELECT * FROM CUSTOM_JOIN_1;

-- EXPORRTING COUNT OF ALL DELAYED FLIGHTS INTO CSV:

COPY 
	(
	WITH FT_DEPT_CTE AS
		(SELECT MONTH, 
		COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE DEPARTURE_DELAY > 0
		GROUP BY MONTH
		),
	FT_ARRIV_CTE AS
		(SELECT MONTH,
		COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE ARRIVAL_DELAY > 0
		GROUP BY MONTH
		),
	
	FT_AIRSYS_CTE AS
		(SELECT MONTH, 
		COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE AIR_SYSTEM_DELAY > 0
		GROUP BY MONTH
		),
	FT_WEATH_CTE AS
		(SELECT MONTH, 
		COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE WEATHER_DELAY > 0
		GROUP BY MONTH
		),
	
	FT_LT_AIRCFT_CTE AS
		(SELECT MONTH, 
		COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE LATE_AIRCRAFT_DELAY > 0
		GROUP BY MONTH
		),
	
	FT_AIRL_CTE AS
		(SELECT MONTH, 
		COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE AIRLINE_DELAY > 0
		GROUP BY MONTH
		),	
	
	FT_SECU_CTE AS
		(SELECT MONTH, 
		COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE DEPARTURE_DELAY > 0
		GROUP BY MONTH
		),
	
	CUSTOM_JOIN_1 AS
		(SELECT F1.MONTH, 
		 COALESCE(F1.DEPARTURE_DELAYED_FLIGHTS,0) AS  DEPARTURE_DELAYED_FLIGHTS,
		 COALESCE(F2.ARRIVAL_DELAYED_FLIGHTS,0) AS  ARRIVAL_DELAYED_FLIGHTS,
		 COALESCE(F3.AIR_SYSTEM_DELAYED_FLIGHTS,0) AS  AIR_SYSTEM_DELAYED_FLIGHTS, 
		 COALESCE(F4.WEATHER_DELAYED_FLIGHTS,0) AS  WEATHER_DELAYED_FLIGHTS,
		 COALESCE(F5.LATE_AIRCRAFT_DELAYED_FLIGHTS,0) AS  LATE_AIRCRAFT_DELAYED_FLIGHTS,
		 COALESCE(F6.SECURITY_DELAYED_FLIGHTS,0) AS  SECURITY_DELAYED_FLIGHTS
		 FROM FT_DEPT_CTE AS F1
		 JOIN FT_ARRIV_CTE  AS F2 
		 ON F1.MONTH = F2.MONTH
		 JOIN FT_AIRSYS_CTE AS F3
		 ON F1.MONTH = F3.MONTH
		 JOIN FT_WEATH_CTE AS F4
		 ON F1.MONTH = F4.MONTH
		 JOIN FT_LT_AIRCFT_CTE AS F5
		 ON F1.MONTH = F5.MONTH
		 JOIN FT_SECU_CTE AS F6
		 ON F1.MONTH = F6.MONTH	 
		)	
		SELECT * FROM CUSTOM_JOIN_1
	)TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/DELAYED_FLIGHTS_COUNTS.csv'
		WITH CSV HEADER;


/* ----------------------------------------- */

/* COUNT OF IN WHICH MOTH EACH TYPES OF FLIGHTS DELAYED HAPPEND MOST*/
		
-- COUNT OF DEPARTURE DELAYED FLIGHTS
 
	SELECT MONTH, 
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH
	ORDER BY DEPARTURE_DELAYED_FLIGHTS DESC;

-- AIRPORT WISE DEPARTURE DELAYED FLIGHTS

	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE DEPARTURE_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY DEPARTURE_DELAYED_FLIGHTS DESC;


/*
	Peak in June & July (over 200K delays), lowest in September & October.
*/

-- COUNT OF ARRIVAL DELAYED FLIGHTS

	SELECT MONTH, 
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0  -- "ARRIVAL_DELAY <= 15 OR ARRIVAL_DELAY >= 15" BASEDD ON THE INSTRUCTIONS, 
						     -- BUT I HAVE COSIDER ALL THOSE FLIGHTS THOSE EVEN 1 MINUTE LATE.
	GROUP BY MONTH
	ORDER BY ARRIVAL_DELAYED_FLIGHTS DESC;


-- AIRPORT WISE ARRIVAL DELAYED FLIGHTS:

	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE ARRIVAL_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY ARRIVAL_DELAYED_FLIGHTS DESC;

/*
	Peak in June & July (over 200K delays), lowest in September & October.
*/

-- COUNT OF AIR SYSTEM DELAYED FLIGHTS

	SELECT MONTH, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH
	ORDER BY AIR_SYSTEM_DELAYED_FLIGHTS DESC;


-- AIRPORT WISE AIR SYSTEM DELAYED FLIGHTS

	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY AIR_SYSTEM_DELAYED_FLIGHTS DESC;

/*
Gradual rise till June, peaking at ~58K, with dip in fall (Sep–Nov)
*/

-- COUNT OF SECURITY DELAYED FLIGHTS

	SELECT MONTH, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE SECURITY_DELAY > 0
	GROUP BY MONTH
	ORDER BY SECURITY_DELAYED_FLIGHTS DESC;

-- AIRPORT WISE SECURITY DELAYED FLIGHTS

	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE SECURITY_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY SECURITY_DELAYED_FLIGHTS DESC;
	

/*
	Most severe in June (105K), with a consistent pattern around ~85K for most months.
*/

-- COUNT OF AIRLINE DELAYED FLIGHTS

	SELECT MONTH, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH
	ORDER BY AIRLINE_DELAYED_FLIGHTS DESC;

-- AIRPORT WISE AIRLINE DELAYED FLIGHTS

	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE AIRLINE_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY AIRLINE_DELAYED_FLIGHTS DESC;

/*
Airline delayed mostly happened in June & July month, may be due rainy season and maintenance required extra care
*/

-- COUNT OF LATE AIRCRAFT DELAYED FLIGHTS

	SELECT MONTH, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH
	ORDER BY LATE_AIRCRAFT_DELAYED_FLIGHTS DESC;

-- AIRPORT WISE LATE AIRCRAFT DELAYED FLIGHTS

	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY LATE_AIRCRAFT_DELAYED_FLIGHTS DESC;

/*
Highest in June (64K), lowest in September & October
*/

-- COUNT OF WEATHER DELAYED FLIGHTS

	SELECT MONTH, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH
	ORDER BY WEATHER_DELAYED_FLIGHTS DESC;


-- AIRPORT WISE LATE WEATHER DELAYED FLIGHTS
	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE WEATHER_DELAY > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY WEATHER_DELAYED_FLIGHTS DESC;

	SELECT * FROM AIRPORTS;
	
/*
	February may see unpredictable winter storms or fog (common in many connecting hubs).
	June could involve summer storms or heat waves.
	
*/

-- COUNT OF DELAYED FLIGHTS BASED ON THE INSTRUCTION

SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
		COUNT(ARRIVAL_DELAY) AS DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE ARRIVAL_DELAY >= -15 AND ARRIVAL_DELAY <= 15
		GROUP BY MONTH,ORIGIN_AIRPORT, DESTINATION_AIRPORT
		ORDER BY DELAYED_FLIGHTS DESC;


-- EXPORTING IN CSV:

COPY
	(
	SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
		COUNT(ARRIVAL_DELAY) AS DELAYED_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE ARRIVAL_DELAY >= -15 AND ARRIVAL_DELAY <= 15
		GROUP BY MONTH,ORIGIN_AIRPORT, DESTINATION_AIRPORT
		ORDER BY DELAYED_FLIGHTS DESC

	)TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/INSTRUCTION_DELAYED_FLIGHTS.csv' 
	WITH CSV HEADER;


/* ----------------------------------------- */

/* FINDING DEPARTURE DELAY IN EACH MONTHS:
		BASED ON HOW MANY FLIGHTS, HOW MANY MINUTES  */
		
SELECT MONTH, DEPARTURE_DELAY AS DEPARTURE_DELAY_MINUTE, 
COUNT(DEPARTURE_DELAY) AS  NO_OF_DELAYED_FLIGHTS
FROM EM_FLIGHTS 
WHERE DEPARTURE_DELAY > 0
GROUP BY MONTH, DEPARTURE_DELAY
ORDER BY NO_OF_DELAYED_FLIGHTS DESC;

/* FINDING EARLY DEPARTURE IN EACH MONTHS:
		BASED ON HOW MANY FLIGHTS, HOW MANY MINUTES */
		

SELECT MONTH, ABS(DEPARTURE_DELAY) AS EARLY_DEPARTURE_MINUTE, 
COUNT(DEPARTURE_DELAY) AS  NO_OF_EARLY_DEPARTURE_FLIGHTS
FROM EM_FLIGHTS 
WHERE DEPARTURE_DELAY < 0  -- WHEN DEPARTURE_DELAY IS IN NEGETIVE
GROUP BY MONTH, DEPARTURE_DELAY
ORDER BY NO_OF_EARLY_DEPARTURE_FLIGHTS DESC;

/* ---------------------------------------------------------------------------------------- */



/* Problem Statement 2:
Benchmarking the on-time performance, delay severity, 
and cancellation rates of different airlines for competitive analysis and improvement initiatives.
*/


/* FINDING ON TIME PERFORMANCE (PERCENTAGE) OF EACH AIRLINE IN EACH MONTHS: */

WITH AIR_L_CTE AS
	(
		SELECT MONTH, AIRLINE,
		COUNT(SCHEDULED_ARRIVAL) AS  ON_TIME_FLIGHTS
		FROM EM_FLIGHTS 
		WHERE 
			ARRIVAL_TIME <= SCHEDULED_ARRIVAL 
			AND ARRIVAL_TIME IS NOT NULL 
			AND CANCELLED = 0
			
		GROUP BY MONTH,AIRLINE
	),
		
	AIR_L_CTE2 AS
		(
		
		SELECT ALC.MONTH, ALC.AIRLINE, 
		ALN.AIRLINE AS AIRLINE_NAME,
		ALC.ON_TIME_FLIGHTS 
		
		FROM AIR_L_CTE AS ALC
		LEFT JOIN AIRLINES AS ALN
		ON ALC.AIRLINE= ALN.IATA_CODE
		ORDER BY ALC.MONTH
		),
		
	AIR_L_CTE3 AS
		(
		
		SELECT
			ALC2.MONTH, 
			ALC2.AIRLINE, 
			ALC2.AIRLINE_NAME, 
			ALC2.ON_TIME_FLIGHTS,
		COUNT(EMF.ARRIVAL_TIME) AS NUMBER_OF_FLIGHTS_FLY
		FROM AIR_L_CTE2 AS ALC2
		JOIN EM_FLIGHTS AS EMF
		ON ALC2.AIRLINE = EMF.AIRLINE
		WHERE EMF.CANCELLED = 0
		GROUP BY 
		    ALC2.MONTH, 
		    ALC2.AIRLINE, 
		    ALC2.AIRLINE_NAME, 
		    ALC2.ON_TIME_FLIGHTS
		ORDER BY ALC2.MONTH
		)
SELECT *, ROUND((ON_TIME_FLIGHTS::NUMERIC /NUMBER_OF_FLIGHTS_FLY)*100, 2) AS ON_TIME_PERCENTAGE
FROM AIR_L_CTE3;


-- FINDING ON TIME PERFORMANCE ON AIRLINES:
	SELECT 
	EMF.AIRLINE AS AIRLINE_IATA, 
	ARL.AIRLINE AS AIRLINE_NAME,
	COUNT(EMF.SCHEDULED_ARRIVAL) AS  ON_TIME_FLIGHTS
	
	FROM EM_FLIGHTS AS EMF
	JOIN AIRLINES AS ARL
	ON EMF.AIRLINE = ARL.IATA_CODE
	
	WHERE EMF.ARRIVAL_TIME <= EMF.SCHEDULED_ARRIVAL AND EMF.ARRIVAL_TIME IS NOT NULL
	GROUP BY EMF.AIRLINE, ARL.AIRLINE
	ORDER BY ON_TIME_FLIGHTS DESC;

SELECT * FROM AIRLINES;

SELECT * FROM EM_FLIGHTS LIMIT 10;

/*

THE SOUTHWEST AIRLINE DELIVER BEST ON TIME PERFORMANCE

*/


-- -- BY AIRLINE
-- 	SELECT MONTH, AIRLINE,
-- 	COUNT(SCHEDULED_ARRIVAL) AS  ON_TIME_FLIGHTS
-- 	FROM EM_FLIGHTS 
-- 	WHERE ARRIVAL_TIME <= SCHEDULED_ARRIVAL AND ARRIVAL_TIME IS NOT NULL
-- 	GROUP BY MONTH,AIRLINE;

-- WORKING ON AIRLINES SCHEDULED_ARRIVAL AND ACTUAL ARRIVAL_TIME

-- FINDING ON TIME PERFORMANCE ON MONTH:

	SELECT MONTH,
	COUNT(SCHEDULED_ARRIVAL) AS  ON_TIME_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_TIME <= SCHEDULED_ARRIVAL
	GROUP BY MONTH
	ORDER BY ON_TIME_FLIGHTS DESC;
/*
POOREST ON TIME PERFORMANCE HAPPENED IN JANUARY AND FEBRUARY MAY BE DUE TO THUNDER STROME, UN EXPECTED MACHINARY PROBLEMS
*/

	SELECT EMF.MONTH, EMF.AIRLINE AS AIRLINE_IATA,
	ARL.AIRLINE AS AIRLINE_NAME,
	COUNT(EMF.SCHEDULED_ARRIVAL) AS  ON_TIME_FLIGHTS
	
	FROM EM_FLIGHTS AS EMF
	JOIN AIRLINES AS ARL
	ON EMF.AIRLINE = ARL.IATA_CODE

	WHERE ARRIVAL_TIME <= SCHEDULED_ARRIVAL
	GROUP BY EMF.MONTH, EMF.AIRLINE, ARL.AIRLINE
	ORDER BY ON_TIME_FLIGHTS DESC;

/*--------------------------------------------------------*/
	
/* PROBLEM 2 PART 2:
FINDING ON DELAY SEVERITY OF EACH AIRLINE IN EACH MONTHS 
*/


WITH FT_DEPT_CTE AS
	(SELECT MONTH, AIRLINE,
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),
FT_ARRIV_CTE AS
	(SELECT MONTH, AIRLINE,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),
FT_WEATH_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

FT_AIRL_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),	

FT_SECU_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.AIRLINE, F1.DEPARTURE_DELAYED_FLIGHTS,
	 F2.ARRIVAL_DELAYED_FLIGHTS,
	 F3.AIR_SYSTEM_DELAYED_FLIGHTS, 
	 F4.WEATHER_DELAYED_FLIGHTS,
	 F5.LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 F6.SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 LEFT JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH AND F1.AIRLINE = F2.AIRLINE
	 LEFT JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH AND F1.AIRLINE = F3.AIRLINE
	 LEFT JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH AND F1.AIRLINE = F4.AIRLINE
	 LEFT JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH AND F1.AIRLINE = F5.AIRLINE
	 LEFT JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	AND F1.AIRLINE = F6.AIRLINE
	),
CUSTOM_JOIN_2 AS
	(
	SELECT MONTH, AIRLINE, 
	COUNT (DEPARTURE_TIME) AS TOTAL_FLIGHTS_DEPARTED FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME IS NOT NULL
	GROUP BY MONTH, AIRLINE
	),
CUSTOM_JOIN_3 AS
	(
	SELECT CJ1.*,
	CJ2.TOTAL_FLIGHTS_DEPARTED
	FROM CUSTOM_JOIN_1 AS CJ1
	JOIN CUSTOM_JOIN_2 AS CJ2
	ON CJ1.MONTH = CJ2.MONTH AND CJ1.AIRLINE = CJ2.AIRLINE
	),
CUSTOM_JOIN_4 AS
	(
	SELECT MONTH, AIRLINE,
	(DEPARTURE_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS DEPARTURE_DELAYED_PERCENTAGE,
	(ARRIVAL_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS ARRIVAL_DELAYED_PERCENTAGE,
	(AIR_SYSTEM_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS AIR_SYSTEM_DELAYED_PERCENTAGE,
	(WEATHER_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS WEATHER_DELAYED_PERCENTAGE,
	(LATE_AIRCRAFT_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS LATE_AIRCRAFT_DELAYED_PERCENTAGE,
	(SECURITY_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS SECURITY_DELAYED_PERCENTAGE
	FROM CUSTOM_JOIN_3
	)


SELECT CJ3.*,
CJ4.DEPARTURE_DELAYED_PERCENTAGE,
CJ4.ARRIVAL_DELAYED_PERCENTAGE ,
CJ4.AIR_SYSTEM_DELAYED_PERCENTAGE ,
CJ4.WEATHER_DELAYED_PERCENTAGE ,
CJ4.LATE_AIRCRAFT_DELAYED_PERCENTAGE ,
CJ4.SECURITY_DELAYED_PERCENTAGE 
FROM CUSTOM_JOIN_4 AS CJ4
JOIN CUSTOM_JOIN_3 AS CJ3
ON CJ3.MONTH = CJ4.MONTH AND CJ3.AIRLINE = CJ4.AIRLINE;



/* ----------------------------------- */

-- EXPORTING DELAY SEVERITY OF EACH AIRLINE IN EACH MONTHS:

COPY 
	(
	WITH FT_DEPT_CTE AS
	(SELECT MONTH, AIRLINE,
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),
FT_ARRIV_CTE AS
	(SELECT MONTH, AIRLINE,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),
FT_WEATH_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

FT_AIRL_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),	

FT_SECU_CTE AS
	(SELECT MONTH, AIRLINE, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.AIRLINE, 
	 COALESCE(F1.DEPARTURE_DELAYED_FLIGHTS, 0) AS DEPARTURE_DELAYED_FLIGHTS,
	 COALESCE(F2.ARRIVAL_DELAYED_FLIGHTS, 0) AS ARRIVAL_DELAYED_FLIGHTS,
	 COALESCE(F3.AIR_SYSTEM_DELAYED_FLIGHTS, 0) AS AIR_SYSTEM_DELAYED_FLIGHTS, 
	 COALESCE(F4.WEATHER_DELAYED_FLIGHTS, 0) AS WEATHER_DELAYED_FLIGHTS,
	 COALESCE(F5.LATE_AIRCRAFT_DELAYED_FLIGHTS, 0) AS LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 COALESCE(F6.SECURITY_DELAYED_FLIGHTS, 0) AS SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 LEFT JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH AND F1.AIRLINE = F2.AIRLINE
	 LEFT JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH AND F1.AIRLINE = F3.AIRLINE
	 LEFT JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH AND F1.AIRLINE = F4.AIRLINE
	 LEFT JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH AND F1.AIRLINE = F5.AIRLINE
	 LEFT JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	AND F1.AIRLINE = F6.AIRLINE
	),
CUSTOM_JOIN_2 AS
	(
	SELECT MONTH, AIRLINE, 
	COUNT (DEPARTURE_TIME) AS TOTAL_FLIGHTS_DEPARTED FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME IS NOT NULL
	GROUP BY MONTH, AIRLINE
	),
CUSTOM_JOIN_3 AS
	(
	SELECT CJ1.*,
	CJ2.TOTAL_FLIGHTS_DEPARTED
	FROM CUSTOM_JOIN_1 AS CJ1
	JOIN CUSTOM_JOIN_2 AS CJ2
	ON CJ1.MONTH = CJ2.MONTH AND CJ1.AIRLINE = CJ2.AIRLINE
	),
CUSTOM_JOIN_4 AS
	(
	SELECT MONTH, AIRLINE,
	ROUND((DEPARTURE_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS DEPARTURE_DELAYED_PERCENTAGE,
	ROUND((ARRIVAL_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS ARRIVAL_DELAYED_PERCENTAGE,
	ROUND((AIR_SYSTEM_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS AIR_SYSTEM_DELAYED_PERCENTAGE,
	ROUND((WEATHER_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS WEATHER_DELAYED_PERCENTAGE,
	ROUND((LATE_AIRCRAFT_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS LATE_AIRCRAFT_DELAYED_PERCENTAGE,
	ROUND((SECURITY_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS SECURITY_DELAYED_PERCENTAGE
	FROM CUSTOM_JOIN_3
	)
SELECT CJ3.*,
	COALESCE(CJ4.DEPARTURE_DELAYED_PERCENTAGE, 0) AS DEPARTURE_DELAYED_PERCENTAGE,
	COALESCE(CJ4.ARRIVAL_DELAYED_PERCENTAGE, 0) AS  ARRIVAL_DELAYED_PERCENTAGE,
	COALESCE(CJ4.AIR_SYSTEM_DELAYED_PERCENTAGE, 0) AS  AIR_SYSTEM_DELAYED_PERCENTAGE,
	COALESCE(CJ4.WEATHER_DELAYED_PERCENTAGE, 0) AS  WEATHER_DELAYED_PERCENTAGE,
	COALESCE(CJ4.LATE_AIRCRAFT_DELAYED_PERCENTAGE, 0)  AS LATE_AIRCRAFT_DELAYED_PERCENTAGE,
	COALESCE(CJ4.SECURITY_DELAYED_PERCENTAGE, 0) AS SECURITY_DELAYED_PERCENTAGE
FROM CUSTOM_JOIN_4 AS CJ4
JOIN CUSTOM_JOIN_3 AS CJ3
ON CJ3.MONTH = CJ4.MONTH AND CJ3.AIRLINE = CJ4.AIRLINE
	) TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/AIRLINES_DELAY_SEVERITY_MONTHS.csv'
	WITH CSV HEADER;



/* PROBLEM 2 PART 2.2:
FINDING ON DELAY SEVERITY OF "EACH AIRLINE FROM DEPARTURE AIRPORT" IN EACH MONTHS 
*/


WITH FT_DEPT_CTE AS
	(SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),
FT_ARRIV_CTE AS
	(SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),
FT_WEATH_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

FT_AIRL_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),	

FT_SECU_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.AIRLINE,F1.ORIGIN_AIRPORT, F1.DEPARTURE_DELAYED_FLIGHTS,
	 F2.ARRIVAL_DELAYED_FLIGHTS,
	 F3.AIR_SYSTEM_DELAYED_FLIGHTS, 
	 F4.WEATHER_DELAYED_FLIGHTS,
	 F5.LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 F6.SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 LEFT JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH AND F1.AIRLINE = F2.AIRLINE AND F1.ORIGIN_AIRPORT = F2.ORIGIN_AIRPORT
	 LEFT JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH AND F1.AIRLINE = F3.AIRLINE AND F1.ORIGIN_AIRPORT = F3.ORIGIN_AIRPORT
	 LEFT JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH AND F1.AIRLINE = F4.AIRLINE AND F1.ORIGIN_AIRPORT = F4.ORIGIN_AIRPORT
	 LEFT JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH AND F1.AIRLINE = F5.AIRLINE AND F1.ORIGIN_AIRPORT = F5.ORIGIN_AIRPORT
	 LEFT JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	AND F1.AIRLINE = F6.AIRLINE AND F1.ORIGIN_AIRPORT = F6.ORIGIN_AIRPORT
	),
CUSTOM_JOIN_2 AS
	(
	SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	COUNT (DEPARTURE_TIME) AS TOTAL_FLIGHTS_DEPARTED FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME IS NOT NULL
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),
CUSTOM_JOIN_3 AS
	(
	SELECT CJ1.*,
	CJ2.TOTAL_FLIGHTS_DEPARTED
	FROM CUSTOM_JOIN_1 AS CJ1
	JOIN CUSTOM_JOIN_2 AS CJ2
	ON CJ1.MONTH = CJ2.MONTH AND CJ1.AIRLINE = CJ2.AIRLINE AND CJ1.ORIGIN_AIRPORT = CJ2.ORIGIN_AIRPORT
	),
CUSTOM_JOIN_4 AS
	(
	SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
		(DEPARTURE_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS DEPARTURE_DELAYED_PERCENTAGE,
		(ARRIVAL_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS ARRIVAL_DELAYED_PERCENTAGE,
		(AIR_SYSTEM_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS AIR_SYSTEM_DELAYED_PERCENTAGE,
		(WEATHER_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS WEATHER_DELAYED_PERCENTAGE,
		(LATE_AIRCRAFT_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS LATE_AIRCRAFT_DELAYED_PERCENTAGE,
		(SECURITY_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100 AS SECURITY_DELAYED_PERCENTAGE
	FROM CUSTOM_JOIN_3
	)

	SELECT CJ3.*,
		CJ4.DEPARTURE_DELAYED_PERCENTAGE,
		CJ4.ARRIVAL_DELAYED_PERCENTAGE ,
		CJ4.AIR_SYSTEM_DELAYED_PERCENTAGE ,
		CJ4.WEATHER_DELAYED_PERCENTAGE ,
		CJ4.LATE_AIRCRAFT_DELAYED_PERCENTAGE ,
		CJ4.SECURITY_DELAYED_PERCENTAGE 
	FROM CUSTOM_JOIN_4 AS CJ4
	JOIN CUSTOM_JOIN_3 AS CJ3
		ON CJ3.MONTH = CJ4.MONTH 
		AND CJ3.AIRLINE = CJ4.AIRLINE 
		AND CJ3.ORIGIN_AIRPORT = CJ4.ORIGIN_AIRPORT
		;


-- EXPORTING DELAY SEVERITY OF EACH AIRLINE FROM ORIGIN_AIRPORT IN EACH MONTHS:

COPY 
	(
	WITH FT_DEPT_CTE AS
	(SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),
FT_ARRIV_CTE AS
	(SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),
FT_WEATH_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

FT_AIRL_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),	

FT_SECU_CTE AS
	(SELECT MONTH, AIRLINE , ORIGIN_AIRPORT, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.AIRLINE,F1.ORIGIN_AIRPORT, 
	 COALESCE(F1.DEPARTURE_DELAYED_FLIGHTS, 0) AS DEPARTURE_DELAYED_FLIGHTS,
	 COALESCE(F2.ARRIVAL_DELAYED_FLIGHTS, 0) AS ARRIVAL_DELAYED_FLIGHTS,
	 COALESCE(F3.AIR_SYSTEM_DELAYED_FLIGHTS, 0) AS AIR_SYSTEM_DELAYED_FLIGHTS, 
	 COALESCE(F4.WEATHER_DELAYED_FLIGHTS, 0) AS WEATHER_DELAYED_FLIGHTS,
	 COALESCE(F5.LATE_AIRCRAFT_DELAYED_FLIGHTS, 0) AS LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 COALESCE(F6.SECURITY_DELAYED_FLIGHTS, 0) AS SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 LEFT JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH AND F1.AIRLINE = F2.AIRLINE AND F1.ORIGIN_AIRPORT = F2.ORIGIN_AIRPORT
	 LEFT JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH AND F1.AIRLINE = F3.AIRLINE AND F1.ORIGIN_AIRPORT = F3.ORIGIN_AIRPORT
	 LEFT JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH AND F1.AIRLINE = F4.AIRLINE AND F1.ORIGIN_AIRPORT = F4.ORIGIN_AIRPORT
	 LEFT JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH AND F1.AIRLINE = F5.AIRLINE AND F1.ORIGIN_AIRPORT = F5.ORIGIN_AIRPORT
	 LEFT JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	AND F1.AIRLINE = F6.AIRLINE AND F1.ORIGIN_AIRPORT = F6.ORIGIN_AIRPORT
	),
CUSTOM_JOIN_2 AS
	(
	SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	COUNT (DEPARTURE_TIME) AS TOTAL_FLIGHTS_DEPARTED FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME IS NOT NULL
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
	),
CUSTOM_JOIN_3 AS
	(
	SELECT CJ1.*,
	CJ2.TOTAL_FLIGHTS_DEPARTED
	FROM CUSTOM_JOIN_1 AS CJ1
	JOIN CUSTOM_JOIN_2 AS CJ2
	ON CJ1.MONTH = CJ2.MONTH AND CJ1.AIRLINE = CJ2.AIRLINE AND CJ1.ORIGIN_AIRPORT = CJ2.ORIGIN_AIRPORT
	),
CUSTOM_JOIN_4 AS
	(
	SELECT MONTH, AIRLINE, ORIGIN_AIRPORT,
	ROUND((DEPARTURE_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS DEPARTURE_DELAYED_PERCENTAGE,
	ROUND((ARRIVAL_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS ARRIVAL_DELAYED_PERCENTAGE,
	ROUND((AIR_SYSTEM_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS AIR_SYSTEM_DELAYED_PERCENTAGE,
	ROUND((WEATHER_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS WEATHER_DELAYED_PERCENTAGE,
	ROUND((LATE_AIRCRAFT_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS LATE_AIRCRAFT_DELAYED_PERCENTAGE,
	ROUND((SECURITY_DELAYED_FLIGHTS::NUMERIC / TOTAL_FLIGHTS_DEPARTED) * 100,2) AS SECURITY_DELAYED_PERCENTAGE
	FROM CUSTOM_JOIN_3
	)

	SELECT CJ3.*,
		COALESCE(CJ4.DEPARTURE_DELAYED_PERCENTAGE, 0) AS DEPARTURE_DELAYED_PERCENTAGE,
		COALESCE(CJ4.ARRIVAL_DELAYED_PERCENTAGE, 0) AS ARRIVAL_DELAYED_PERCENTAGE,
		COALESCE(CJ4.AIR_SYSTEM_DELAYED_PERCENTAGE, 0) AS AIR_SYSTEM_DELAYED_PERCENTAGE,
		COALESCE(CJ4.WEATHER_DELAYED_PERCENTAGE, 0) AS WEATHER_DELAYED_PERCENTAGE,
		COALESCE(CJ4.LATE_AIRCRAFT_DELAYED_PERCENTAGE, 0) AS LATE_AIRCRAFT_DELAYED_PERCENTAGE,
		COALESCE(CJ4.SECURITY_DELAYED_PERCENTAGE, 0) AS SECURITY_DELAYED_PERCENTAGE
	FROM CUSTOM_JOIN_4 AS CJ4
	JOIN CUSTOM_JOIN_3 AS CJ3
		ON CJ3.MONTH = CJ4.MONTH 
		AND CJ3.AIRLINE = CJ4.AIRLINE 
		AND CJ3.ORIGIN_AIRPORT = CJ4.ORIGIN_AIRPORT

	) TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/AIRLINES_AIRPORT_MONTHLY_DELAYED.csv'
	WITH CSV HEADER;


/* PROBLEM 2 PART 3:
FINDING ON CANCELLATION SEVERITY RATES OF EACH AIRLINE FROM ORIGIN AIRPORT IN EACH MONTHS 
*/

-- AIRLINE>AIROPRT MONTHLY CANCELLATION GROUP BY CANCELLATION_REASON:

WITH FT_CANCELLED_CTE AS
	(SELECT MONTH, AIRLINE, ORIGIN_AIRPORT, CANCELLATION_REASON,
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE CANCELLED = 1
	GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT, CANCELLATION_REASON
	)
SELECT * FROM FT_CANCELLED_CTE;

-- AIRLINE>AIROPRT MONTHLY CANCELLATION PERCENTAGE:

WITH FT_CANCEL2_CTE AS
		(
		SELECT 
			MONTH, 
			AIRLINE, 
			ORIGIN_AIRPORT,
			COUNT(SCHEDULED_DEPARTURE) AS SCHEDULED_FLIGHTS_COUNT,
			COUNT(CASE WHEN CANCELLED = 1 THEN 1 END) AS CANCELLED_FLIGHTS
		FROM EM_FLIGHTS 
		GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
		),
FT_CANCEL2_PERCENT AS
		(
		SELECT *, 
		ROUND ((CANCELLED_FLIGHTS::NUMERIC/ SCHEDULED_FLIGHTS_COUNT)*100, 2) AS CANCELLED_FT_PERCENT
		FROM FT_CANCEL2_CTE
		)
SELECT * FROM FT_CANCEL2_PERCENT;

-- AIRPORT WISE CANCELLED_FLIGHTS
	SELECT EMF.ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, ARP1.AIRPORT AS ORIGIN_AIRPORT_NAME,
	EMF.DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, ARP2.AIRPORT AS DESTINATION_AIRPORT_NAME,
	COUNT(EMF.CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS AS EMF
	JOIN AIRPORTS AS ARP1
	ON EMF.ORIGIN_AIRPORT = ARP1.IATA_CODE
	
	JOIN AIRPORTS AS ARP2
	ON EMF.DESTINATION_AIRPORT = ARP2.IATA_CODE
	
	WHERE CANCELLED > 0
	GROUP BY EMF.ORIGIN_AIRPORT, EMF.DESTINATION_AIRPORT, ARP1.AIRPORT, ARP2.AIRPORT
	ORDER BY CANCELLED_FLIGHTS ASC
	-- ORDER BY CANCELLED_FLIGHTS ASC
	;

-- MONTH WISE CANCELLED_FLIGHTS

SELECT 
	MONTH, 
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS
	WHERE CANCELLED> 0 OR  CANCELLED=1
	GROUP BY MONTH
ORDER BY CANCELLED_FLIGHTS DESC;

	
	-- SELECT * FROM AIRPORTS;
	
-- EXPORTING CANCELLATION SEVERITY RATES OF EACH AIRLINE FROM ORIGIN AIRPORT IN EACH MONTHS:

	COPY
		(
		WITH FT_CANCEL2_CTE AS
			(
			SELECT 
				MONTH, 
				AIRLINE, 
				ORIGIN_AIRPORT,
				COUNT(SCHEDULED_DEPARTURE) AS SCHEDULED_FLIGHTS_COUNT,
				COUNT(CASE WHEN CANCELLED = 1 THEN 1 END) AS CANCELLED_FLIGHTS
			FROM EM_FLIGHTS 
			GROUP BY MONTH, AIRLINE, ORIGIN_AIRPORT
			),
		FT_CANCEL2_PERCENT AS
					(
					SELECT *, 
					ROUND ((CANCELLED_FLIGHTS::NUMERIC/ SCHEDULED_FLIGHTS_COUNT)*100, 2) AS CANCELLED_FT_PERCENT
					FROM FT_CANCEL2_CTE
					)
		SELECT * FROM FT_CANCEL2_PERCENT
		) 
		TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/AIRLINES_AIRPORT_MONTHLY_CANCELLED.csv'
		WITH CSV HEADER;



-- AIRLINE MONTHLY CANCELLATION PERCENTAGE:

WITH FT_CANCEL2_CTE AS
		(
		SELECT 
			MONTH, 
			AIRLINE,
			COUNT(SCHEDULED_DEPARTURE) AS SCHEDULED_FLIGHTS_COUNT,
			COUNT(CASE WHEN CANCELLED = 1 THEN 1 END) AS CANCELLED_FLIGHTS
		FROM EM_FLIGHTS 
		GROUP BY MONTH, AIRLINE
		),
FT_CANCEL2_PERCENT AS
		(
		SELECT *, 
		ROUND ((CANCELLED_FLIGHTS::NUMERIC/ SCHEDULED_FLIGHTS_COUNT)*100, 2) AS CANCELLED_FT_PERCENT
		FROM FT_CANCEL2_CTE
		)
SELECT * FROM FT_CANCEL2_PERCENT
ORDER BY CANCELLED_FT_PERCENT DESC;


-- FROM ORIGIN AIRPORTS MONTHLY CANCELLATION PERCENTAGE:

WITH FT_CANCEL2_CTE AS
		(
		SELECT 
			MONTH, 
			ORIGIN_AIRPORT,
			COUNT(SCHEDULED_DEPARTURE) AS SCHEDULED_FLIGHTS_COUNT,
			COUNT(CASE WHEN CANCELLED = 1 THEN 1 END) AS CANCELLED_FLIGHTS
		FROM EM_FLIGHTS 
		GROUP BY MONTH, ORIGIN_AIRPORT
		),
FT_CANCEL2_PERCENT AS
		(
		SELECT *, 
		ROUND ((CANCELLED_FLIGHTS::NUMERIC/ SCHEDULED_FLIGHTS_COUNT)*100, 2) AS CANCELLED_FT_PERCENT
		FROM FT_CANCEL2_CTE
		)
SELECT * FROM FT_CANCEL2_PERCENT
ORDER BY CANCELLED_FT_PERCENT DESC;


-- CANCELLATION PATTERN/REASONS BASED ON THE TRAVELLING ROUTS:

WITH CR_CTE AS 
	(
	SELECT ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, 
	DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, 
	CANCELLATION_REASON,
	COUNT(CANCELLED) AS CANCELLATION_COUNT
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY ORIGIN_AIRPORT, DESTINATION_AIRPORT, CANCELLATION_REASON
	ORDER BY CANCELLATION_COUNT DESC
	),
ARP_CTE AS 
	(
	SELECT ARP.IATA_CODE, ARP.AIRPORT AS ORIGIN_AIRPORT,
	ARP.CITY AS ORIGIN_CITY,
	ARP2.IATA_CODE AS DESTINATION_IATA_CODE,
	ARP2.AIRPORT AS DESTINATION_AIRPORT,
	ARP2.CITY AS DESTINATION_CITY
	FROM AIRPORTS AS ARP
	JOIN AIRPORTS AS ARP2
	ON ARP.IATA_CODE =ARP2.IATA_CODE
	),

FINAL_OUTPUT AS
	(
	select CRC.ORIGIN_AIRPORT_IATA,
	ARPC.ORIGIN_AIRPORT,
	ARPC.ORIGIN_CITY,
	
	CRC.DESTINATION_AIRPORT_IATA,
	ARPC2.DESTINATION_AIRPORT,
	ARPC2.DESTINATION_CITY,
	
	CRC.CANCELLATION_REASON,
	CRC.CANCELLATION_COUNT
	FROM CR_CTE AS CRC
	JOIN ARP_CTE AS ARPC
	ON CRC.ORIGIN_AIRPORT_IATA =ARPC.IATA_CODE
	
	JOIN ARP_CTE AS ARPC2
	ON CRC.DESTINATION_AIRPORT_IATA =ARPC2.DESTINATION_IATA_CODE
	)
SELECT * FROM FINAL_OUTPUT;


-- EXPORTING CANCELLATION PATTERN/REASONS BASED ON THE TRAVELLING ROUTS

COPY 
	(
	WITH CR_CTE AS 
	(
	SELECT ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, 
	DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, 
	CANCELLATION_REASON,
	COUNT(CANCELLED) AS CANCELLATION_COUNT
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY ORIGIN_AIRPORT, DESTINATION_AIRPORT, CANCELLATION_REASON
	ORDER BY CANCELLATION_COUNT DESC
	),
ARP_CTE AS 
	(
	SELECT ARP.IATA_CODE, ARP.AIRPORT AS ORIGIN_AIRPORT,
	ARP.CITY AS ORIGIN_CITY,
	ARP2.IATA_CODE AS DESTINATION_IATA_CODE,
	ARP2.AIRPORT AS DESTINATION_AIRPORT,
	ARP2.CITY AS DESTINATION_CITY
	FROM AIRPORTS AS ARP
	JOIN AIRPORTS AS ARP2
	ON ARP.IATA_CODE =ARP2.IATA_CODE
	),

FINAL_OUTPUT AS
	(
	select CRC.ORIGIN_AIRPORT_IATA,
	ARPC.ORIGIN_AIRPORT,
	ARPC.ORIGIN_CITY,
	
	CRC.DESTINATION_AIRPORT_IATA,
	ARPC2.DESTINATION_AIRPORT,
	ARPC2.DESTINATION_CITY,
	
	CRC.CANCELLATION_REASON,
	CRC.CANCELLATION_COUNT
	FROM CR_CTE AS CRC
	JOIN ARP_CTE AS ARPC
	ON CRC.ORIGIN_AIRPORT_IATA =ARPC.IATA_CODE
	
	JOIN ARP_CTE AS ARPC2
	ON CRC.DESTINATION_AIRPORT_IATA =ARPC2.DESTINATION_IATA_CODE
	)
SELECT * FROM FINAL_OUTPUT

	) 
	TO 'D:\Data Analytics\Intership\Labmentix\Emirates_Flight Analysis\SUBMISSION\CUSTOM CSV\CANCEL_REASONS_ON_ROUTS.csv' 
WITH CSV HEADER;

-- ------------------------------------------------

/* ---------------------------------------------------------------------------------------- */

/* Problem Statement 3:
Evaluating the operational performance of various U.S. airports 
to identify bottlenecks and areas for infrastructure or process improvement.
*/


SELECT MONTH, ORIGIN_AIRPORT,
COUNT(ARRIVAL_TIME) AS ON_TIME_FLIGHTS
	FROM EM_FLIGHTS
	WHERE ARRIVAL_TIME<= SCHEDULED_ARRIVAL AND  ARRIVAL_TIME IS NOT NULL
	GROUP BY MONTH, ORIGIN_AIRPORT
	ORDER BY ON_TIME_FLIGHTS DESC;

-- ----
SELECT * FROM EM_FLIGHTS LIMIT 1000;

-- ORIGIN AND DESTINATION AIRPORTS GROUP BY OPERATIONS:

WITH FT_ON_TIME_CTE AS (
	SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(ARRIVAL_TIME) AS ON_TIME_FLIGHTS
		FROM EM_FLIGHTS
		WHERE ARRIVAL_TIME<= SCHEDULED_ARRIVAL AND  ARRIVAL_TIME IS NOT NULL
		GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_CANCELLED_CTE AS
	(
	SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_DEPT_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
	
FT_ARRIV_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
FT_WEATH_CTE AS
	(SELECT MONTH,ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_AIRL_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),	

FT_SECU_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH,  ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.ORIGIN_AIRPORT, F1.DESTINATION_AIRPORT, F1.DEPARTURE_DELAYED_FLIGHTS,
	 F2.ARRIVAL_DELAYED_FLIGHTS,
	 F3.AIR_SYSTEM_DELAYED_FLIGHTS, 
	 F4.WEATHER_DELAYED_FLIGHTS,
	 F5.LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 F6.SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 LEFT JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH AND F1.ORIGIN_AIRPORT = F2.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F2.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH AND F1.ORIGIN_AIRPORT = F3.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F3.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH AND F1.ORIGIN_AIRPORT = F4.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F4.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH AND F1.ORIGIN_AIRPORT = F5.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F5.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	AND F1.ORIGIN_AIRPORT = F6.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F6.DESTINATION_AIRPORT
	),
CUSTOM_JOIN_2 AS
	(
	SELECT MONTH, ORIGIN_AIRPORT,DESTINATION_AIRPORT,
	COUNT (DEPARTURE_TIME) AS TOTAL_FLIGHTS_DEPARTED FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME IS NOT NULL
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
CUSTOM_JOIN_3 AS
	(
	SELECT CJ1.*,
	CJ2.TOTAL_FLIGHTS_DEPARTED
	FROM CUSTOM_JOIN_1 AS CJ1
	JOIN CUSTOM_JOIN_2 AS CJ2
	ON CJ1.MONTH = CJ2.MONTH AND CJ1.ORIGIN_AIRPORT = CJ2.ORIGIN_AIRPORT AND CJ1.DESTINATION_AIRPORT = CJ2.DESTINATION_AIRPORT
	),
CUSTOM_JOIN_4 AS
	(
	SELECT FTON.*,
	COALESCE(FTCN.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS, -- COALESCE( FILL THE NULL VALUES WITH 0)
	COALESCE(CJ3.DEPARTURE_DELAYED_FLIGHTS, 0) AS DEPARTURE_DELAYED_FLIGHTS,
	COALESCE(CJ3.ARRIVAL_DELAYED_FLIGHTS, 0) AS ARRIVAL_DELAYED_FLIGHTS,
	COALESCE(CJ3.AIR_SYSTEM_DELAYED_FLIGHTS, 0) AS AIR_SYSTEM_DELAYED_FLIGHTS, 
	COALESCE(CJ3.WEATHER_DELAYED_FLIGHTS, 0) AS WEATHER_DELAYED_FLIGHTS,
	COALESCE(CJ3.LATE_AIRCRAFT_DELAYED_FLIGHTS, 0) AS LATE_AIRCRAFT_DELAYED_FLIGHTS,
	COALESCE(CJ3.SECURITY_DELAYED_FLIGHTS, 0) AS SECURITY_DELAYED_FLIGHTS
	FROM FT_ON_TIME_CTE AS FTON
	LEFT JOIN CUSTOM_JOIN_3 AS CJ3
	ON FTON.MONTH = CJ3.MONTH AND FTON.ORIGIN_AIRPORT = CJ3.ORIGIN_AIRPORT AND FTON.DESTINATION_AIRPORT = CJ3.DESTINATION_AIRPORT
	LEFT JOIN FT_CANCELLED_CTE AS FTCN
	ON FTON.MONTH = FTCN.MONTH AND FTON.ORIGIN_AIRPORT = FTCN.ORIGIN_AIRPORT AND FTON.DESTINATION_AIRPORT = FTCN.DESTINATION_AIRPORT
	)
SELECT * FROM CUSTOM_JOIN_4;




-- EXPORTING EACH ORIGIN AND DESTINATION AIRPORTS FLIGHTS STATS IN EACH MONTHS:
-- REPLACED THE NULL VALUE COUNTS WITH "0"
	/* COALESCE() returns the "first non-NULL value" from the list of arguments.
			So "if column_name is NULL", it will "return 0".*/

COPY
	(
	WITH FT_ON_TIME_CTE AS (
	SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(ARRIVAL_TIME) AS ON_TIME_FLIGHTS
		FROM EM_FLIGHTS
		WHERE ARRIVAL_TIME<= SCHEDULED_ARRIVAL AND  ARRIVAL_TIME IS NOT NULL
		GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_CANCELLED_CTE AS
	(
	SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_DEPT_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(DEPARTURE_DELAY) AS DEPARTURE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
	
FT_ARRIV_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(ARRIVAL_DELAY) AS ARRIVAL_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE ARRIVAL_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_AIRSYS_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(AIR_SYSTEM_DELAY) AS AIR_SYSTEM_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIR_SYSTEM_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
FT_WEATH_CTE AS
	(SELECT MONTH,ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(WEATHER_DELAY) AS WEATHER_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE WEATHER_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_LT_AIRCFT_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(LATE_AIRCRAFT_DELAY) AS LATE_AIRCRAFT_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE LATE_AIRCRAFT_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

FT_AIRL_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(AIRLINE_DELAY) AS AIRLINE_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE AIRLINE_DELAY > 0
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),	

FT_SECU_CTE AS
	(SELECT MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
	COUNT(SECURITY_DELAY) AS SECURITY_DELAYED_FLIGHTS
	FROM EM_FLIGHTS 
	WHERE DEPARTURE_DELAY > 0
	GROUP BY MONTH,  ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),

CUSTOM_JOIN_1 AS
	(SELECT F1.MONTH, F1.ORIGIN_AIRPORT, F1.DESTINATION_AIRPORT, F1.DEPARTURE_DELAYED_FLIGHTS,
	 COALESCE(F2.ARRIVAL_DELAYED_FLIGHTS, 0) AS ARRIVAL_DELAYED_FLIGHTS,
	 COALESCE(F3.AIR_SYSTEM_DELAYED_FLIGHTS, 0) AS AIR_SYSTEM_DELAYED_FLIGHTS, 
	 COALESCE(F4.WEATHER_DELAYED_FLIGHTS, 0) AS WEATHER_DELAYED_FLIGHTS,
	 COALESCE(F5.LATE_AIRCRAFT_DELAYED_FLIGHTS, 0) AS LATE_AIRCRAFT_DELAYED_FLIGHTS,
	 COALESCE(F6.SECURITY_DELAYED_FLIGHTS, 0) AS SECURITY_DELAYED_FLIGHTS
	 FROM FT_DEPT_CTE AS F1
	 LEFT JOIN FT_ARRIV_CTE  AS F2 
	 ON F1.MONTH = F2.MONTH AND F1.ORIGIN_AIRPORT = F2.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F2.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_AIRSYS_CTE AS F3
	 ON F1.MONTH = F3.MONTH AND F1.ORIGIN_AIRPORT = F3.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F3.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_WEATH_CTE AS F4
	 ON F1.MONTH = F4.MONTH AND F1.ORIGIN_AIRPORT = F4.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F4.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_LT_AIRCFT_CTE AS F5
	 ON F1.MONTH = F5.MONTH AND F1.ORIGIN_AIRPORT = F5.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F5.DESTINATION_AIRPORT
	 
	 LEFT JOIN FT_SECU_CTE AS F6
	 ON F1.MONTH = F6.MONTH	AND F1.ORIGIN_AIRPORT = F6.ORIGIN_AIRPORT AND F1.DESTINATION_AIRPORT = F6.DESTINATION_AIRPORT
	),
CUSTOM_JOIN_2 AS
	(
	SELECT MONTH, ORIGIN_AIRPORT,DESTINATION_AIRPORT,
	COUNT (DEPARTURE_TIME) AS TOTAL_FLIGHTS_DEPARTED FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME IS NOT NULL
	GROUP BY MONTH, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
CUSTOM_JOIN_3 AS
	(
	SELECT CJ1.*,
	CJ2.TOTAL_FLIGHTS_DEPARTED
	FROM CUSTOM_JOIN_1 AS CJ1
	JOIN CUSTOM_JOIN_2 AS CJ2
	ON CJ1.MONTH = CJ2.MONTH AND CJ1.ORIGIN_AIRPORT = CJ2.ORIGIN_AIRPORT AND CJ1.DESTINATION_AIRPORT = CJ2.DESTINATION_AIRPORT
	),
CUSTOM_JOIN_4 AS
	(
	SELECT FTON.*,
	COALESCE(FTCN.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS, 
    COALESCE(CJ3.DEPARTURE_DELAYED_FLIGHTS, 0) AS DEPARTURE_DELAYED_FLIGHTS,
    COALESCE(CJ3.ARRIVAL_DELAYED_FLIGHTS, 0) AS ARRIVAL_DELAYED_FLIGHTS,
    COALESCE(CJ3.AIR_SYSTEM_DELAYED_FLIGHTS, 0) AS AIR_SYSTEM_DELAYED_FLIGHTS,
    COALESCE(CJ3.WEATHER_DELAYED_FLIGHTS, 0) AS WEATHER_DELAYED_FLIGHTS,
    COALESCE(CJ3.LATE_AIRCRAFT_DELAYED_FLIGHTS, 0) AS LATE_AIRCRAFT_DELAYED_FLIGHTS,
    COALESCE(CJ3.SECURITY_DELAYED_FLIGHTS, 0) AS SECURITY_DELAYED_FLIGHTS
	FROM FT_ON_TIME_CTE AS FTON
	LEFT JOIN CUSTOM_JOIN_3 AS CJ3
	ON FTON.MONTH = CJ3.MONTH AND FTON.ORIGIN_AIRPORT = CJ3.ORIGIN_AIRPORT AND FTON.DESTINATION_AIRPORT = CJ3.DESTINATION_AIRPORT
	LEFT JOIN FT_CANCELLED_CTE AS FTCN
	ON FTON.MONTH = FTCN.MONTH AND FTON.ORIGIN_AIRPORT = FTCN.ORIGIN_AIRPORT AND FTON.DESTINATION_AIRPORT = FTCN.DESTINATION_AIRPORT
	)
SELECT *

FROM CUSTOM_JOIN_4

	) TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/AIRPORTS_MONTHLY_DEPT_ARIVE_STATS.csv' 
	WITH CSV HEADER;



/* ---------------------------------------------------------------------------------------- */


/* Problem Statement 4:
Investigating how factors like time of day, day of week, month, 
and specific routes affect flight operations to optimize scheduling and resource allocation.
*/

-- DAY WISE OPERATION
-- -- DELAY OPERATION
-- 1)
SELECT DAY, COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
	FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
	GROUP BY DAY
	ORDER BY DELAY_FLIGHTS_PER_DAY DESC;

-- -- MONTH & DAY OPERATION
--1)
SELECT MONTH, DAY, COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
	FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
	GROUP BY MONTH, DAY
	ORDER BY DELAY_FLIGHTS_PER_DAY DESC;

-- 2)
SELECT MONTH, DAY, COUNT(DEPARTURE_TIME) AS ON_TIME_FLIGHTS_DAY
	FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME<= SCHEDULED_DEPARTURE AND CANCELLED = 0 
	GROUP BY MONTH, DAY
	ORDER BY ON_TIME_FLIGHTS_DAY DESC;

-- FINAL STATS: MONTH - DAY_OF_WEEK - DEPARTURE_TIME_BUCKET

-- PART 1:
WITH MONTHDAY_ONTIME_FTE AS
	(
	SELECT MONTH, DAY,DEPARTURE_TIME_BUCKET, 
	COUNT(DEPARTURE_TIME) AS ON_TIME_FLIGHTS_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME<= SCHEDULED_DEPARTURE AND CANCELLED = 0 
		GROUP BY MONTH, DAY,DEPARTURE_TIME_BUCKET
		ORDER BY ON_TIME_FLIGHTS_DAY DESC
		),
DELAYED_FT_CTE AS
	(
	SELECT MONTH, DAY,DEPARTURE_TIME_BUCKET,
	COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
		GROUP BY MONTH, DAY, DEPARTURE_TIME_BUCKET
	),
CANCELLED_FT_CTE AS 
	(
	SELECT MONTH, DAY, DEPARTURE_TIME_BUCKET,
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY MONTH, DAY, DEPARTURE_TIME_BUCKET
	),
DATE_STATS AS
	(
	SELECT MDOF.*,
	COALESCE(DFC.DELAY_FLIGHTS_PER_DAY, 0) AS DELAY_FLIGHTS_PER_DAY, 
	COALESCE(CFC.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS
	FROM MONTHDAY_ONTIME_FTE AS MDOF
	
	LEFT JOIN DELAYED_FT_CTE AS DFC
	ON MDOF.MONTH = DFC.MONTH AND MDOF.DAY = DFC.DAY AND MDOF.DEPARTURE_TIME_BUCKET = DFC.DEPARTURE_TIME_BUCKET

	LEFT JOIN CANCELLED_FT_CTE AS CFC
	ON MDOF.MONTH = CFC.MONTH AND MDOF.DAY = CFC.DAY AND MDOF.DEPARTURE_TIME_BUCKET = CFC.DEPARTURE_TIME_BUCKET
	)
SELECT * FROM DATE_STATS;

-- PART 2:



WITH MONTHDAY_ONTIME_FTE AS
	(
	SELECT MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(DEPARTURE_TIME) AS ON_TIME_FLIGHTS_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME<= SCHEDULED_DEPARTURE AND CANCELLED = 0 
		GROUP BY MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT
		ORDER BY MONTH
		),
DELAYED_FT_CTE AS
	(
	SELECT MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
		GROUP BY MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
CANCELLED_FT_CTE AS 
	(
	SELECT MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT
	),
DATE_STATS AS
	(
	SELECT MDOF.*,
	COALESCE(DFC.DELAY_FLIGHTS_PER_DAY, 0) AS DELAY_FLIGHTS_PER_DAY, 
	COALESCE(CFC.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS
	FROM MONTHDAY_ONTIME_FTE AS MDOF
	
	LEFT JOIN DELAYED_FT_CTE AS DFC
	ON MDOF.MONTH = DFC.MONTH AND MDOF.DAY = DFC.DAY AND MDOF.ORIGIN_AIRPORT = DFC.ORIGIN_AIRPORT AND MDOF.DESTINATION_AIRPORT = DFC.DESTINATION_AIRPORT

	LEFT JOIN CANCELLED_FT_CTE AS CFC
	ON MDOF.MONTH = CFC.MONTH AND MDOF.DAY = CFC.DAY AND MDOF.ORIGIN_AIRPORT = CFC.ORIGIN_AIRPORT AND MDOF.DESTINATION_AIRPORT = CFC.DESTINATION_AIRPORT
	)
SELECT * FROM DATE_STATS;

-- EXPORTING THE DATA
-- -- PART 1

COPY 
	(
	WITH MONTHDAY_ONTIME_FTE AS
	(
	SELECT MONTH, DAY,DEPARTURE_TIME_BUCKET, 
	COUNT(DEPARTURE_TIME) AS ON_TIME_FLIGHTS_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME<= SCHEDULED_DEPARTURE AND CANCELLED = 0 
		GROUP BY MONTH, DAY,DEPARTURE_TIME_BUCKET
		ORDER BY ON_TIME_FLIGHTS_DAY DESC
		),
DELAYED_FT_CTE AS
	(
	SELECT MONTH, DAY,DEPARTURE_TIME_BUCKET,
	COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
		GROUP BY MONTH, DAY, DEPARTURE_TIME_BUCKET
	),
CANCELLED_FT_CTE AS 
	(
	SELECT MONTH, DAY, DEPARTURE_TIME_BUCKET,
	COUNT(CANCELLED) AS CANCELLED_FLIGHTS
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY MONTH, DAY, DEPARTURE_TIME_BUCKET
	),
DATE_STATS AS
	(
	SELECT MDOF.*,
	COALESCE(DFC.DELAY_FLIGHTS_PER_DAY, 0) AS DELAY_FLIGHTS_PER_DAY, 
	COALESCE(CFC.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS
	FROM MONTHDAY_ONTIME_FTE AS MDOF
	
	LEFT JOIN DELAYED_FT_CTE AS DFC
	ON MDOF.MONTH = DFC.MONTH AND MDOF.DAY = DFC.DAY AND MDOF.DEPARTURE_TIME_BUCKET = DFC.DEPARTURE_TIME_BUCKET

	LEFT JOIN CANCELLED_FT_CTE AS CFC
	ON MDOF.MONTH = CFC.MONTH AND MDOF.DAY = CFC.DAY AND MDOF.DEPARTURE_TIME_BUCKET = CFC.DEPARTURE_TIME_BUCKET
	)
SELECT * FROM DATE_STATS

	) TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/M.D.T_FLIGHTS_STATS.csv' 
	WITH CSV HEADER;




-- -- PART 2

COPY 
	(
	 WITH MONTHDAY_ONTIME_FTE AS
	(
	 SELECT MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT,
	 COUNT(DEPARTURE_TIME) AS ON_TIME_FLIGHTS_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME<= SCHEDULED_DEPARTURE AND CANCELLED = 0 
		GROUP BY MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT
		ORDER BY MONTH
	),
	DELAYED_FT_CTE AS
		(
		SELECT MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT,
		COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
			FROM EM_FLIGHTS
			WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
			GROUP BY MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT
		),
	CANCELLED_FT_CTE AS 
		(
		SELECT MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
		COUNT(CANCELLED) AS CANCELLED_FLIGHTS
		FROM EM_FLIGHTS
		WHERE CANCELLED = 1
		GROUP BY MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT
		),
	DATE_STATS AS
		(
		SELECT MDOF.*,
		COALESCE(DFC.DELAY_FLIGHTS_PER_DAY, 0) AS DELAY_FLIGHTS_PER_DAY, 
		COALESCE(CFC.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS
		FROM MONTHDAY_ONTIME_FTE AS MDOF
		
		LEFT JOIN DELAYED_FT_CTE AS DFC
		ON MDOF.MONTH = DFC.MONTH AND MDOF.DAY = DFC.DAY AND MDOF.ORIGIN_AIRPORT = DFC.ORIGIN_AIRPORT AND MDOF.DESTINATION_AIRPORT = DFC.DESTINATION_AIRPORT
	
		LEFT JOIN CANCELLED_FT_CTE AS CFC
		ON MDOF.MONTH = CFC.MONTH AND MDOF.DAY = CFC.DAY AND MDOF.ORIGIN_AIRPORT = CFC.ORIGIN_AIRPORT AND MDOF.DESTINATION_AIRPORT = CFC.DESTINATION_AIRPORT
		)
	SELECT * FROM DATE_STATS

	)TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/M.D_ORG.DEST_FT_STATS.csv' 
	WITH CSV HEADER;






-- -- PART 3 MONTH-DAY-AIRLINE-ORIGIN_AIRPORT-DESTINATION_AIRPORT WISE DATA

COPY 
	(
	 WITH MONTHDAY_ONTIME_FTE AS
	(
	 SELECT MONTH,DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT,AIRLINE, 
	 COUNT(DEPARTURE_TIME) AS ON_TIME_FLIGHTS_DAY
		FROM EM_FLIGHTS
		WHERE DEPARTURE_TIME<= SCHEDULED_DEPARTURE AND CANCELLED = 0 
		GROUP BY MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT, AIRLINE
		ORDER BY MONTH
	),
	DELAYED_FT_CTE AS
		(
		SELECT MONTH, DAY,ORIGIN_AIRPORT, DESTINATION_AIRPORT, AIRLINE,
		COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_PER_DAY
			FROM EM_FLIGHTS
			WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
			GROUP BY MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT, AIRLINE
		),
	CANCELLED_FT_CTE AS 
		(
		SELECT MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT, AIRLINE,
		COUNT(CANCELLED) AS CANCELLED_FLIGHTS
		FROM EM_FLIGHTS
		WHERE CANCELLED = 1
		GROUP BY MONTH, DAY, ORIGIN_AIRPORT, DESTINATION_AIRPORT, AIRLINE
		),
	DATE_STATS AS
		(
		SELECT MDOF.*,
		COALESCE(DFC.DELAY_FLIGHTS_PER_DAY, 0) AS DELAY_FLIGHTS_PER_DAY, 
		COALESCE(CFC.CANCELLED_FLIGHTS, 0) AS CANCELLED_FLIGHTS
		FROM MONTHDAY_ONTIME_FTE AS MDOF
		
		LEFT JOIN DELAYED_FT_CTE AS DFC
		ON MDOF.MONTH = DFC.MONTH AND MDOF.DAY = DFC.DAY AND MDOF.ORIGIN_AIRPORT = DFC.ORIGIN_AIRPORT AND MDOF.DESTINATION_AIRPORT = DFC.DESTINATION_AIRPORT
	
		LEFT JOIN CANCELLED_FT_CTE AS CFC
		ON MDOF.MONTH = CFC.MONTH AND MDOF.DAY = CFC.DAY AND MDOF.ORIGIN_AIRPORT = CFC.ORIGIN_AIRPORT AND MDOF.DESTINATION_AIRPORT = CFC.DESTINATION_AIRPORT
		)
	SELECT * FROM DATE_STATS

	)TO 'D:/Data Analytics/Intership/Labmentix/Emirates_Flight Analysis/SUBMISSION/CUSTOM CSV/M.D_AIRL_OR_DES_STATS.csv' 
	WITH CSV HEADER;











SELECT *
	FROM EM_FLIGHTS LIMIT 100;


-- DAY_OF_WEEK WISE OPERATION: WHICH DAYS IN A WEEK MOST DELAYED HAPPEN
-- -- DELAY OPERATION
-- 1)

SELECT DAY_OF_WEEK, COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_DAY_WEEK
	FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
	GROUP BY DAY_OF_WEEK
	ORDER BY DELAY_FLIGHTS_DAY_WEEK DESC;

-- -- MONTH & DAY_OF_WEEK OPERATION

SELECT MONTH, DAY_OF_WEEK, COUNT(DEPARTURE_TIME) AS DELAY_FLIGHTS_DAY_WEEK
	FROM EM_FLIGHTS
	WHERE DEPARTURE_TIME> SCHEDULED_DEPARTURE
	GROUP BY MONTH, DAY_OF_WEEK
	ORDER BY DELAY_FLIGHTS_DAY_WEEK DESC;

	

/* ---------------------------------------------------------------------------------------- */


/* Problem Statement 5:
Providing data-driven recommendations to stakeholders (airlines, airports, regulatory bodies) 
to enhance passenger experience and operational efficiency.
*/


WITH CR_CTE AS 
	(
	SELECT ORIGIN_AIRPORT AS ORIGIN_AIRPORT_IATA, 
	DESTINATION_AIRPORT AS DESTINATION_AIRPORT_IATA, 
	CANCELLATION_REASON,
	COUNT(CANCELLED) AS CANCELLATION_COUNT
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY ORIGIN_AIRPORT, DESTINATION_AIRPORT, CANCELLATION_REASON
	ORDER BY CANCELLATION_COUNT DESC
	),
ARP_CTE AS 
	(
	SELECT ARP.IATA_CODE, ARP.AIRPORT AS ORIGIN_AIRPORT,
	ARP.CITY AS ORIGIN_CITY,
	ARP2.IATA_CODE AS DESTINATION_IATA_CODE,
	ARP2.AIRPORT AS DESTINATION_AIRPORT,
	ARP2.CITY AS DESTINATION_CITY
	FROM AIRPORTS AS ARP
	JOIN AIRPORTS AS ARP2
	ON ARP.IATA_CODE =ARP2.IATA_CODE
	),

FINAL_OUTPUT AS
	(
	select CRC.ORIGIN_AIRPORT_IATA,
	ARPC.ORIGIN_AIRPORT,
	ARPC.ORIGIN_CITY,
	
	CRC.DESTINATION_AIRPORT_IATA,
	ARPC2.DESTINATION_AIRPORT,
	ARPC2.DESTINATION_CITY,
	
	CRC.CANCELLATION_REASON,
	CRC.CANCELLATION_COUNT
	FROM CR_CTE AS CRC
	JOIN ARP_CTE AS ARPC
	ON CRC.ORIGIN_AIRPORT_IATA =ARPC.IATA_CODE
	
	JOIN ARP_CTE AS ARPC2
	ON CRC.DESTINATION_AIRPORT_IATA =ARPC2.DESTINATION_IATA_CODE
	)
SELECT * FROM FINAL_OUTPUT;



SELECT ORIGIN_AIRPORT, DESTINATION_AIRPORT, CANCELLATION_REASON,
	COUNT(CANCELLED) AS CANCELLATION_COUNT
	FROM EM_FLIGHTS
	WHERE CANCELLED = 1
	GROUP BY ORIGIN_AIRPORT, DESTINATION_AIRPORT, CANCELLATION_REASON
	ORDER BY CANCELLATION_COUNT DESC;


SELECT *
	FROM AIRPORTS LIMIT 100;

SELECT DISTINCT(MONTH)
	FROM EM_FLIGHTS;


/* ---------------------------------------------------------------------------------------- */


SELECT * FROM EM_FLIGHTS limit 10000;
SELECT DISTINCT ORIGIN_AIRPORT FROM EM_FLIGHTS;

/*

ARRIVAL_DELAY float,
DIVERTED   float,
CANCELLED  float,
CANCELLATION_REASON  object,
AIR_SYSTEM_DELAY float,
SECURITY_DELAY float,
AIRLINE_DELAY float,
LATE_AIRCRAFT_DELAY   float,
WEATHER_DELAY        float

*/

